### ISSUE TITLE
Wrong layout in 1.0.7 when input is short

### ISSUE THREAD

**Issue by xak2000** [ruhley/angular-color-picker#70]
Afger upgrading to 1.0.7 the layout is broken if input width is small.

https://plnkr.co/edit/vqmYT5wKXVcQMkeG8D0T?p=preview (Make preview viewport wider then 768 px to display `form-inline` properly).

Also the vertical align is broken too. Try to comment `vertical-align: middle;` in custom `.color-picker-wrapper` css. This is broken after 1.0 actually (when bootstrap removed), but this can be easily workaround. But layout bug introduced in 1.0.7 is not so easy.

I tried this plunkr with CSS from version 1.0.6 and layout is fine.

**Comment by xak2000** [comment]
I think PR #68 is bad. Using relative positioning is wrong here.

**Comment by ruhley** [comment]
If I change the css in the plunker to 

```css
.issue-label-form .color-picker-input-wrapper {
  display: inline-block;
  vertical-align: middle;
  width: auto;
}
```

then it works fine for me.
